#!/usr/bin/env bash
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=dwl
export GDK_BACKEND=wayland
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export CLUTTER_BACKEND=wayland
export MOZ_ENABLE_WAYLAND=1

exec dwl < <(someblocks -p)
