#!/usr/bin/env bash
set -euo pipefail

WP_OPT=${1:+-i "$1"}
: "${WP_OPT:=-c 333332}"

LOCKCMD="swaylock -f $WP_OPT"

swayidle -w \
    timeout 300 "$LOCKCMD" \
    timeout 305 "wlr-randr --output eDP-1 --off" \
    resume "wlr-randr --output eDP-1 --on"
