#!/usr/bin/env bash
set -euo pipefail

if WP=$(randfile "$HOME/pictures/wallpapers"); then
    WP_OPT="-i \"$WP\""
else
    WP_OPT="-c 333332"
fi

LOCKCMD="swaylock -f $WP_OPT"

swayidle -w \
    timeout 300  "$LOCKCMD" \
    timeout 305 "wlr-randr --output eDP-1 --off" \
    resume  "wlr-randr --output eDP-1 --on" \
 
